# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcea07445a2a35b086b633523f530b22e83407b662f3a98b4909a6e9e9544cb2437cb1dd646c0dbc33cb540ebb0c04fa2958148278211f21cf128c9852c08b91

test:
  secret_key_base: 97f90226dea2bd5008327513b95233c05dd76263439615b3da11f7ae3e9321eda70ecd25be203af0472c547920bcd1114d5e265d44435bedd58bd87a0fcfc22a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
